name: roadside_heroes_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0

  dotted_line: ^3.2.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1

  im_stepper: ^1.0.1+1
  image_picker: ^1.0.7
  image_sequence_animator: ^2.0.0
  provider: ^6.1.2
  syncfusion_flutter_gauges: ^25.1.35


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Medium.ttf
        - asset: assets/fonts/Gilroy-ExtraBold.ttf
          style: normal
        - asset: assets/fonts/Gilroy-Regular.ttf
        - asset: assets/fonts/Gilroy-SemiBold.ttf


  
